#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
barriers --daemon --name krastiva --config ~/.config/barrier/barrier_config --debug INFO --disable-crypto --address :24800
$HOME/.config/polybar/launch.sh &


